apiVersion: v1
kind: Pod
metadata:
  name: result-web
spec:
  containers:
  - image: registry-vpc.cn-beijing.aliyuncs.com/eci_open/nginx:latest
    name: web
    ports:
      - name: web-port
        containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: jmeter-volume
  volumes:
  - name: "jmeter-volume"
    flexVolume:
      driver: "alicloud/oss"
      options:
        bucket: "jmeter-result"
        url: "oss-cn-beijing-internal.aliyuncs.com"
        otherOpts: "-o max_stat_cache_size=0 -o allow_other"
        ramRole: "EciOssRoleShare"