apiVersion: v1
kind: Pod
metadata:
  name: result-web
spec:
  containers:
  - image: registry-vpc.cn-beijing.aliyuncs.com/eci_open/nginx:latest
    name: web
    ports:
      - name: web-port
        containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: jmeter-volume
      subPath: jmeter/result/nginx   #NFS中的子目录
  volumes:
  - name: jmeter-volume
    nfs:
      server: 1fe5c4aa7d-****.cn-beijing.nas.aliyuncs.com  #NFS挂载点
      path: /
      readOnly: true